config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                        Controller#Action
#         root GET    /                                  pages#home
#        users POST   /users(.:format)                   users#create
#         user PATCH  /users/:id(.:format)               users#update
#              PUT    /users/:id(.:format)               users#update
#         tags POST   /tags(.:format)                    tags#create
#          tag DELETE /tags/:id(.:format)                tags#destroy
#     glossary DELETE /glossaries/:id(.:format)          glossaries#destroy
#         node DELETE /nodes/:id(.:format)               nodes#destroy
#        login GET    /login(.:format)                   session#new
#              POST   /login(.:format)                   session#create
#              DELETE /login(.:format)                   session#destroy
#     new_user GET    /signup(.:format)                  users#new
#       folder GET    /:urlname(.:format)                users#folders
#  folder_edit GET    /:urlname/edit(.:format)           users#foldedit
#       search GET    /:urlname/search(.:format)         users#search
#      profile GET    /:urlname/profile(.:format)        users#profile
# profile_edit GET    /:urlname/profile/edit(.:format)   users#edit
#              POST   /:urlname/profile/edit(.:format)   users#update
#     new_page GET    /:urlname/newpage(.:format)        pages#new
#              POST   /:urlname/:pagename(.:format)      pages#create
#         view GET    /:urlname/:pagename(.:format)      pages#view
#         edit GET    /:urlname/:pagename/edit(.:format) pages#edit
#              POST   /:urlname/:pagename(.:format)      pages#update
#              GET    /:folderId/add(.:format)           nodes#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'

  resources :users, :only => [:create, :update]
  resources :tags, :only => [:create, :destroy]
  resources :glossaries, :only => [:create, :destroy]
  resources :nodes, :only => [:create, :destroy]
  resources :image_blocks, :only => [:create, :destroy]
  resources :text_blocks, :only => [:create, :destroy]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/signup' => 'users#new', as: 'new_user'

  get '/:urlname' => 'users#folders', as: 'folder'
  get '/:urlname/edit' => 'users#foldedit', as: 'folder_edit'

  get '/:urlname/search' => 'users#search', as: 'search'

  get '/:urlname/profile' => 'users#profile', as: 'profile'

  get '/:urlname/profile/edit' => 'users#edit', as: 'profile_edit'
  post '/:urlname/profile/edit' => 'users#update'

  get '/:urlname/newpage' => 'pages#new', as: 'new_page'
  post '/:urlname/:pagename' => 'pages#create'

  get '/:urlname/:pagename' => 'pages#view', as: 'view'

  get '/:urlname/:pagename/edit' => 'pages#edit', as: 'edit'
  post '/:urlname/:pagename' => 'pages#update'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :text
#  password_digest :text
#  email           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#  urlname         :text
#

class User < ApplicationRecord
  has_secure_password
  has_many :tags
  has_many :nodes
  has_many :glossaries

  validates :email, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true
  validates :urlname, :presence => true, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.urlname = @user.username.gsub(" ","-").downcase
    root = Node.new :name => 'root'
    @user.nodes.push(root)

    if @user.save
      session[:user_id] = @user.id
      redirect_to folder_path(@user.urlname)
    else
      render :new
    end
  end

  def folders
    @user = User.find_by :urlname => params[:urlname]
    render :unknown unless @user.present?
  end

  def foldedit
    @user = User.find_by :urlname => params[:urlname]
    redirect_to profile_path(params[:urlname]) unless session[:user_id] == @user.id
  end

  def search
    @user = User.find_by :urlname => params[:urlname]
  end

  def profile
    @user = User.find_by :urlname => params[:urlname]
  end

  def edit
    @user = User.find_by :urlname => params[:urlname]
    redirect_to profile_path(params[:urlname]) unless session[:user_id] == @user.id
  end

  def update
    puts '-=' * 40
    user = User.find_by :id => params[:id]
    user.update user_params
    user.urlname = user.username.gsub(" ","-").downcase
    if user.save
      redirect_to profile_path(user.urlname)
    else
      flash[:invaliderror] = "Username or email is already in use"
      redirect_to profile_edit_path(user.urlname)
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<h1>Edit Things</h1>

<div class="ajax-reloadable">

<%= flash[:invaliderror] %>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "Change Details"%>
<% end %>

<%= flash[:tagerror] %>
<h3>Tags</h3>
<div>
  <% @user.tags.each do |tag| %>
  <p><%= tag.name %><%= button_to "Delete", tag_path(tag.id), :method => :delete, remote: true, :class => 'tag-delete' %></p>
  <% end %>
</div>

<%= form_for Tag.new, :remote => true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit 'New Tag', :class => 'tag-submit-button' %>
<% end %>

<%= flash[:glosserror] %>
<h3>Glossaries</h3>
<div>
  <% @user.glossaries.each do |gloss| %>
  <p><%= link_to gloss.title, edit_path(@user.urlname, gloss.urlname)  %><%= button_to "Delete", glossary_path(gloss.id), :method => :delete, remote: true %></p>
  <% end %>
</div>

<%= form_for Glossary.new, :remote => true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit 'New Glossary', :class => 'gloss-submit-button' %>
<% end %>

</div>

app/views/users/foldedit.html.erb
<!-- tree += "<input class='new-dir' type='button' onclick='newDir()'>" -->
<!-- tree += "<input class='new-gloss' type='button' onclick='newGloss()'>" -->

<h1>Edit Directory</h1>

<div class='ajax-reloadable'>

  <p><%= flash[:nodeerror] %></p>

  <%= form_for Node.new, :remote => true do %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    <%= hidden_field_tag :user_id, value: @user.id %>
    <%= submit_tag 'Create' %>
    <%= label_tag :id, "Root Directory"%>
    <%= radio_button_tag :id, "#{(@user.nodes.find_by :name => 'root').id}", true %>

    <div id="folder-tree-2">
       <%== editableChildren @user.nodes[0] %>
    </div>
    <% end %>
</div>

<!-- TODO make folders deletable -->
<%# <%= button_to "Delete", node_path(node.id), :method => :delete, remote: true %>

app/views/users/folders.html.erb
<h1>Directory</h1>

<%= link_to "Search", search_path %>

<div class="ajax-reloader" id="folder-tree">
    <%== openAll @user.nodes[0] %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <%  %>
  </ul>
  <% end %>
<% end %>

<%= form_for @user, html: {class: "nifty_form"} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up"%>
<% end %>

app/views/users/profile.html.erb
<h1><%= @user.username %> Profile</h1>

<%= link_to @user.username + "'s Files", user_path(@user.urlname)%>

<h3>Tags</h3>
<p>
<% @user.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>
</p>

<h3>Glossaries</h3>
<div>
  <% @user.glossaries.each do |gloss| %>
  <p><%= link_to gloss.title, edit_path(@user.urlname, gloss.urlname)  %><%= button_to "Delete", glossary_path(gloss.id), :method => :delete, remote: true %></p>
  <% end %>
</div>

app/views/users/search.html.erb
<h1>Search</h1>

<%= @user.tags %>

app/views/users/unknown.html.erb
<h1>Unknown user</h1>